@URL = http://localhost:3000/api

GET {{URL}}/clientes
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjEwLCJpYXQiOjE3NjM2NjI0MDl9.z8qZ0YGmSs4veW_TmhIM3Net-oYd1tynXMAtwSqrdjM
###
GET {{URL}}/clientes/146
###
PUT {{URL}}/clientes/150
Content-Type: application/json

{
  "nombre": "Juanan",
  "apellidos": "gomez",
  "direccion": "1Hetr",
  "email": "anasr@imageshack.us",
  "edad": 28,
  "genero": "M",
  "cuota": 16.90,
  "fecha_nacimiento": "2010-04-27",
  "dni": "309632997g"
}

###
POST {{URL}}/clientes
Content-Type: application/json

{
  "nombre": "Alvar",
  "apellidos": "Gron",
  "direccion": "1Hetr",
  "email": "alvar@imageshack.us",
  "edad": 28,
  "genero": "M",
  "fecha_inscripcion": "2025-04-09T16:00:00",
  "cuota": 16.90,
  "fecha_nacimiento": "2010-04-27",
  "dni": "309632997g",
  "monitores_id": 21,
  "staff_id": 12
}

###
DELETE {{URL}}/clientes/150

###
POST {{URL}}/usuarios/registro
Content-Type: application/json

{
  "username":"req",
  "email":"crede@mail.com",
  "password":"12345",
  "rol":"admin"
}

###
POST {{URL}}/usuarios/login
Content-Type: application/json

{
  "email":"crede@mail.com",
  "password":"12345"
}